# Generated by Django 4.0.3 on 2022-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountscustomuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
