# Generated by Django 4.0.3 on 2022-04-11 18:32

import ProjectSoftUni.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', validators=[ProjectSoftUni.common.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
